name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rust setup
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - name: Install libudev
        run: |
          sudo apt-get install libudev-dev
      - name: Check build errors
        run: cargo build
